<?
// $Id$

/**
 * @file sws-map-field.tpl.php
 * Default theme implementation to display the value of a map field.
 *
 * Available variables:
 * - $node: The node object.
 * - $map: Google Map, generated by embed_gmap module.
 *
 * @see template_preprocess_sws_map()
 */
?>

<?php if (!empty($map)) : ?>
  <div class='map <?php print $type ?>-map'><?php print $map ?></div>
<?php endif; ?>
